Check that an overlay is visible before removing
fayaz07/ots pull request #17
Opened 2020-10-03 17:06 UTC by alexandradeas

Add a guard to ensure that before `_hideOverlay` removes an overlay that
there is currently a visible entry of that overlay type. This resolves
an issue which would cause the flutter engine to throw as
`AssertionError` if either `hideLoader` or `hideNotification` are called
whilst no overlay of that type is currently showing.

closes #16

2020-10-08 17:19 UTC, fayaz07 requested changes
Hi @alexandradeas , can you please add a `debugPrint` statement there which states, `No overlay is shown`

this should appear if the user doesn't really show it and just tried to hide it

2020-10-08 18:00 UTC, alexandradeas commented
@fayaz07 done

2020-10-09 03:57 UTC, fayaz07 approved these changes

2020-10-09 04:00 UTC, fayaz07 commented
I observed you also added tests there, why should'n't we run them whenever someone pushes the code, can you please make a PR for setting up github workflow.?

2020-10-09 04:00 UTC, merged

2020-10-09 04:01 UTC, fayaz07 commented
@Allcontributors please add @alexandradeas

2020-10-09 04:04 UTC, fayaz07 commented
@all-contributors please add @alexandradeas for code

2020-10-09 05:42 UTC, fayaz07 commented
@all-contributors please add me @fayaz07  for code, content, data, doc, doc, example, ideas, maintenance, mentoring